/**
 * Formats an array of chrome.cookies.Cookie objects into Netscape cookies.txt format.
 * This is the standard format used by curl, wget, and other HTTP tools.
 *
 * NEVER sends data outside the browser — everything stays on your device.
 */
export function formatCookiesTxt(cookies) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by Pagex — open source, everything stays on your device.',
    '# This file contains cookies exported for the selected tab.',
    '',
  ];

  for (const cookie of cookies) {
    const domain = cookie.domain;
    const isDomainWide = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = cookie.expirationDate
      ? Math.floor(cookie.expirationDate)
      : 0;
    const name = cookie.name;
    const value = cookie.value;

    lines.push(
      [domain, isDomainWide, path, secure, expiry, name, value].join('\t'),
    );
  }

  return lines.join('\n') + '\n';
}
